# used for data preprocessing:

results_dir:  '/home/dev/data_main/LOGS/SR_ESPCN/baseline/trial_02'
data: '/home/dev/data_main/DIV2K'
data_hr:  '/home/dev/data_main/DIV2K/HR'
data_lr:  '/home/dev/data_main/DIV2K/LR'

data_processed_hr: '/home/dev/data_main/DIV2K/processed_50_espcn/HR'
data_processed_lr: '/home/dev/data_main/DIV2K/processed_50_espcn/LR'
val_folder: '/valid/'
train_folder: '/train/'
scale: 4
patch_size: 50
stride: 60

subset: #'/home/dev/work_main/2021/RAW_SELECTION/subset_1.0%_KCenters.txt'
rank_items: false
save_model: '/home/dev/data_main/LOGS/SR_ESPCN/baseline/trial_02/'
# TRANING
load_weiths: #'/home/dev/work_main/2021/crcnn/resutls/epoch_25.909.pth'

device: 1
seed: 777
lr: 1e-3
batch_size: 32
num_workers: 10
num_epochs: 20

log_step : 100 
save_steps: 1000

benchmark: false # use true for reproducibility 
